# Generated by Django 5.1.2 on 2024-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='consolexpress/')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=75)),
                ('marca', models.CharField(max_length=75)),
                ('precio', models.CharField(max_length=75)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
