# Generated by Django 5.1.2 on 2024-10-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_consolas/'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
