# Generated by Django 5.1.2 on 2024-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0002_alter_consola_imagen_alter_consola_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(upload_to='img_consolas/'),
        ),
    ]
