# Generated by Django 5.1.2 on 2024-10-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0003_alter_consola_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='categoria',
            field=models.CharField(choices=[('consola', 'Consola'), ('especial', 'Especial'), ('accesorio', 'Accesorio')], max_length=20),
        ),
    ]
