# Generated by Django 5.1.2 on 2024-11-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0004_alter_consola_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='presentacion',
            field=models.CharField(choices=[('paquete_completo', 'Paquete completo'), ('individual', 'Individual')], default='individual', max_length=20),
        ),
    ]
