# Generated by Django 5.1.2 on 2024-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0005_consola_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
