# Generated by Django 5.1.2 on 2024-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0006_alter_consola_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
