# Generated by Django 5.1.2 on 2024-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolexpress', '0007_alter_consola_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True)),
                ('titular', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('tipo_tarjeta', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
